#ifndef EXT_INTERRUPTS_H_
#define EXT_INTERRUPTS_H_
#include "EXT_Interrupts_Registers.h"
#include "BitMath.h"
#include <avr/interrupt.h>
typedef enum
{
	EXT_INTERRUPT0=0,
	EXT_INTERRUPT1,
	EXT_INTERRUPT2,
	}EXT_INTERRUPT_Types;
typedef enum
{
	LOW_LEVEL=0,
	BOTH_EDGES,
	FALLING_EDGE,
	RISING_EDGE
	}SNC_MODE_Types;
typedef enum
{
	EXT_INTERRUPT_ENABLE=0,
	EXT_INTERRUPT_DISABLE,
	}EXT_INTERRUPT_STATE_Types;

void EXT_INTERRUPTS_STATE(EXT_INTERRUPT_Types INTERRUPT_NO,EXT_INTERRUPT_STATE_Types STATE);
void EXT_INTERRUPTS_SNCONTROLE_MODE(EXT_INTERRUPT_Types INTERRUPT_NO,SNC_MODE_Types MODE);
void EXT_INTERRUPTS_SetCallBack(EXT_INTERRUPT_Types INTERRUPT_NO,void (*EXT_INTERRUPT_FUNCTION_COPY_PTR)(void));
#endif